apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:bpZl9pNN57hmDW672y8Hnj2g7ABPk0I837zNU298xicv6+KxKVF82uItO74yPDoY9oiQD0voRcIrWwKPyxDLxHMEYOy5Hw2N4bUemBnZYMr3LYLwUY3adaKRDUTPt6SZmL89c0fKnaERVrI0f+FKMra79yw16mR+M2n18r3zK+5GJdVRrY6Io/97AREcREYE6/MknoM57QDLLRJBGL4Xm0Q3G7wW2R9h8PUy8LXTwxvZBqCAsqa6Q+d08udkMTbo81dtFOdRUBnFQY8rf+LJ3Lw39G7NhiKMlldTiNwx3zwWMvixA2T99HYsFN9qwftclVrsSd+nH2tJi/o2652Z+P/lh5UFImEvAPpgK87RHN8+zUuOXKJ9x2T/OzX2txJB,iv:knb05gzLJTvK062YNZEbUtwq/GE459oBpXTrdaCPx5E=,tag:ZEUFtMiQsyQOr7RJqZynFg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ihisep53VIqv2DvEW1STCQXc8rmUW1xRUV4u+bMUF9L7GQ+B1J4FsC3HyVzB2OBh/uoymdk1sGJcepMkobe9peRjNCkkEDN7/urJO4tFI/E3I/CLKuXuwNij0avWcs91dXlyqtZzVil0OrSL8OL0wU/Viqy+E8r5Lr+BOYnfCf+tQkCwhkDaFZ1kWhnenZ+HM8VkQIEx4KCwCON3/JLSIh13u/lrfZiVEG6PEM1cImMKoAEC1DRf3gIoxNYqp8GwCFhz5Cr9Wl2bxmmApA==,iv:kkTLAV3oX5oHq+t7P2tsSiRH4kberiZzI8k8Dn3dcn4=,tag:FimgPPedyJSg/TEhdC5AxQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:K+0WjEpOXL+2Oq7G9SkMii8Ixxsg9qBMn2Zb2jOHN05mCjT+Oamcb9Dx4WQ8c9u5tjoRtYAdaV76BB0qQtZQjkDhwN5gm7+CS9QG2wEgPcLyMo69pv7g0p3kKojC77nuisxcHxfJLZLtkBZelly1UZ9cACB5QzMAL5wF6I1ngGdPmAIW66w2zsEWMdM+9Hn5fgdaUkDLrbsKJAopuV17fjTRAfy0XZ8rWk/k,iv:DCDxAh3BZSSU/PvZawtsQRq/9kf9FTgMOru/JEW/H9w=,tag:hO+yraIcOPfr4VtY+vaPNA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1grv49vt8y6u7vse4030mgnfylx6c2jw7hlwhqs34nc9n9rpdwefqnr7vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNUo5VzFtS2Z4QWo5elJC
            bkZpc2FVUUpBbkZlUndTZGt0YjNBRkFvNERnClhpZ05rSFQ3b1NFMUUvOFU5cyt6
            blN1VFdCaGZ5NkdLa3VrU0J0WFdQOWsKLS0tIDYxcnE2MFZuN3RCSWZvRTV5QlVr
            bmxud1hCYlh3dHV2aWVoZFF2SkZMc3cKAJuyiieXK6UulhwTtLxd7nTv4ZxIIIGu
            fPKdyaDfv65zg5/PPIPsOdJjKNmGqTeEuUoPodKaqC+AMLy8rbCCHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T00:12:34Z"
    mac: ENC[AES256_GCM,data:TkwEzh6JAkjbaYQvE4jA30XJiW6HgT7RheD4EKpDPosihxd2md0aZJZBd9b9lWB5b2E0VKOQtSrIBSJuo/vR6Oj0BOC5aJpL6ehu1OZ1QtZH5jMal2n81T6PQWNv3/BVlgdmn8TSUDZSjndcrzwvYhPoZYUzSEYk7EvKLQGjGfk=,iv:bfVhHnzEZtoLQ17YMOfuS4t09VqZluIgAlllvZLPWd8=,tag:VJwcVzBOpmLcFBa+rRGIJg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
