apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:0tdLR772CMv9gh/jDxO/+LpB6JS8WN0GEF2/1hFJf8EdeZgK8VxGk3FNktekCaeQ2yNjBPLZW3269EspSsawIW5np8lMsBsCIzMnuj8xgWKWFaajEsqSEHmTik9NBk8mRBNeo3ICDgnniILLcoXfzl1kj2vgWO1W32oXul+KdeHdTaHp2eKi72PBzv+yD1MSsyXYBRe0JKcRjD1asHQYsSyv40PxJFpZzjeTZ5e1KA+qqfVQw2jxqEJ1XmAeci8FVP1wlsrdsnGGZ3MiSfDyusAfPc4lcRFXuQ584f9OFTuTt7bxj76LqRxaUc568xMiHlx+SdAcT+XtHbS67fX2C9Y6au7DmzJBHrZRxCfDQJ5VgZI14gKqKbKaO+YpVdvq,iv:4+ROj1hAYKPLzaOQahm13vRLbJVvyj/WSjdcPqjEYf0=,tag:hA8OtLHdZIjVVC5hyhjOpw==,type:str]
    identity.pub: ENC[AES256_GCM,data:a5t/tzZRT36axfnyb/fMaQ5t54DGLKIlRitxMbjKrN5srEJ+D2IqJLcGbJgtl140r1z8O1CfcIfLCghEj0omXNXtSDBpUk5Gt2fivw8VFXgLXBNS29VQcoRbg7kGA+BRhJ1tq16W3dVK+ZJR1DuII5fI8jTnghVRmQVB/1Sec3DnJu0x0tFvqecaAmol0VnSZar1q1Mz4jAdcB0YITpt6DBw01U0UpRQdRi13SF7QJQWHE0vKKnNQknK/1v98t6UbZbIbLOYayr3TiHtEA==,iv:Mg5rL51/Hld/OXGGsVMo/2Zl5aYIc2JgyrDtFW0F8cU=,tag:RpziBrO5B+9c9vHiLSUMoA==,type:str]
    known_hosts: ENC[AES256_GCM,data:2YlGp2Wetss2YWJaLstbFpZi0nx1JS+nu/6s+uc4O9UmjC162WXDbcRj+x1db1w1+eT3UQ4lmAbK58pEygZKg0m8/2AdDNK5T1J3vo/nZCCzAXxw6AQAutVkraz4uwBYggtrMonrGW6xfyPVB23u7b0+v7rMZigPTUn0b7a1IVrQ0jSkTr28yJXRItf8yfOw86SBVDteU9v8kuLee9lTusDYJS8sDTUSXEJD,iv:H/joXDNWBvxbkKAqJg1JFp4oXfiAkE2B7vOWBQs6tk0=,tag:o6lbejDkosQao0Y0Hh+N6Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1grv49vt8y6u7vse4030mgnfylx6c2jw7hlwhqs34nc9n9rpdwefqnr7vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaWdzRTRPQnoyQW1XcjlZ
            ejBPVVBTdDNsQ3puUnVxZXgycG53aG5VL3pFClo4eHAzeEhzNkFyMVdHUTEvUXU3
            L3lvY0I5TGJOSEhwa3dRV3JPUVVRdTQKLS0tIGlEL0R5ZmNJbldRVFJHUlNCMEx5
            Z3FPbVJTa1VYY21tTVNDWExqOTlFWmcKitc+Yf7Vj83eyWubZKifruNu6YU8F3r3
            t3CnTtB6BQBqXuMNvZ5aMC03b+q1qRFB0DQE2Vs3taRHcPw0q/cK/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T03:10:36Z"
    mac: ENC[AES256_GCM,data:M+s9peezpyGaVXbeqCBQ/2jfbu9dX7g2Dcrq9zhK3dbNDF+GjtUyuXIMF1Jin9ob3Cwik3y1PIjiyr83lQbFcBRthX/txhpyMpK2/6K4ch2m+GKUZzcAKsdodufmX83fgashm+3V8d4y+r2GgliP09cWhepV4lfr/Bu45zkBlhM=,iv:1mevV5AtrDASvPDN/N2lK7psIiKsHSaOTjmfAEg4gUA=,tag:xhXI+pjyeiN7NEZSqn2djA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
