apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:nlbHLOpkeimWw7Vk5YHGrX3VadU4lCubWmv4yFM9ryrRjGwTdaXT9r/YX/sRJ3tWiSwm8yu0j4gF+RhMT8PNp3Tb6mRhZRZDreNG0/sZymC7k0dFXKRhd7hYUjL/xEKDUrZMSJci5+zJK4ISgAWM2iuaJfM5QwpuD6iraM73EKcTuNw3bDC4MwjBWXSUXDteq/mQ6L8a1iJatN6p7SBgvXuvXGvgy7BOCDfQ0zauotKiV1F8re1Wsi1kmdoQDU8i+nArDj9+v/Vhpxc8QrrtPi14RAXxRRnZfkKXl0byp/LpfL7DfHdQBA57X76rMFajbLLVCM0uhszedJWBf1XkPjd52tD2zodhTDJPsvPxlrYa1b1eHm7c3fz55VcIF/7q,iv:/RFuMxK1Fcu2mPiLDDZSmmaQqnyhV20d5G0H1jjZByU=,tag:vVJCGJ94huE/2egu9/Cwzg==,type:str]
    identity.pub: ENC[AES256_GCM,data:6e7/COoOf8IkDb7bdJJUz5MrTMtXwv2XmmZtpMxj6O8UqZJE/QPVslqhXp/U112dKXSdpAOFa7rHMZpVo0uZUo/H2t6dgNXG04H04aW4abY+tnH93j+NarJpMQP+NtwayvS+ph2eDHgV6/N8xXZZyTQ6+mPdhpijBFU6zdgp4nknE/ajQ0Ttof034+FHWGYT4Ze//xdbFHzTTGyXmxQDsW3MYWz0UCrRFnKlIJNIpsjMTUd05i4b7+mPDudAS33UHV5BIy2aXxTkYPuVvg==,iv:gifFSXfKJTlZOjCVvFcoV6VHfiqzwmflAGC9TWI88dc=,tag:xvdbX71iUGzmTSE3+U7R2A==,type:str]
    known_hosts: ENC[AES256_GCM,data:cw6MpmfnM6z9C8lNgEvafQrlx3JlW3ViBPXbo0oDH/2MlA5Tg03kjkzJfNWDSA3p1wM//gTOdUqEh87nuCY92AXOHPJwS9LmAyrc0url9AHUKmdnLJwJbMWU+iUl0v6nFTJDiyLAowKp5l+XT+uRZ+pv6naDyfukiLws+Qg0Ehi2OcwtjX0Gxqxdf+xhi13hsRwPw9kfTxdN+UrIPFggmXVvpdNevPeG2kh6,iv:D5j8gbLflULOSsu26E2s7Wpwz2maWE0j+7d+0AEjdU4=,tag:sWLTDyQOHurcyDyTDNhuAA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1grv49vt8y6u7vse4030mgnfylx6c2jw7hlwhqs34nc9n9rpdwefqnr7vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Ymh6T2dMSVBmODBqRzkz
            eHVSVDBOVVFPd1plNDFSbTliYVdMajhBWDBzCkZyMk9RS095RDRpSVpYVHJOUU1l
            Smp4bTBYbVVrUStWUHhtOVVvcmpvcUkKLS0tIG1TRTdnVWdFbWFkc09WemU1cERR
            ZDlDTkNWQVdnUmtubmJ3Qzl4YmRKbmMKqbMLddiI9lMP5HSTkNDhlEoM3JtEo67w
            NHmJepLIxPb/UXrJgi0FNDJ4RAr+TSsJMUu8yuBV+Wha/fgi4Dc9Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T01:51:34Z"
    mac: ENC[AES256_GCM,data:D+9R8fsCak8DEmfsjz+JS+pjFd+gcetoVghgVtXDEJmOKkc/roHGGGdZVnwZXFdqnM9La33EwFuJjHZTxJU+eNcg5bpjg2mDTTT8J9SoqbqzVtdDZAmDRl8G1uz5xdNE0IkzoI9fBvDvLjKaQJxqeV+ST+UsuqbjwaGkd6Z6Xrk=,iv:uC03zV6OH6g4PANPZyTJgH1NqyGWCU+piGG47DXmA/0=,tag:iTWPd4BRplIA2TdrBSx4Vg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
