apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jblm4fwVmiz/EdcHuUjZ7YVfBnvywGLqytXa7SdlnR4fybN0AfYK/XVtK9d3M8f/+42K4PB3Z7ZUieH0rXZ6ELfOTE00HSqjRd6oTbPz5atBphPTL4GZKj6IRBY4PdT1ggHr5J1OmWdo3g+ekk0Dw8PU7eu57VxH9/j3DSCja9ZFeBBGeD9l1aELaEX8g6rIbMApYP/SBlJnDodPrTYqYN5S6uDgHmDahufg14wIfsYZC3teqYk2C2Yl/AoJckiCXN8ZyI5N24Y4koANlvRwOKdbuI3pn8pOUL6Tay59qTtO4orYWi/4an3m247uGlC31X/D7Vcj3szcNDAQZxVfOWRvT7CAW40geh800EFTu5hBZw8h9PKYDf1/8nMF4sX+,iv:B880IvYJASIa/LAVMckiiYBhjbfdB8NzESnl5R+25Sk=,tag:cJcRNozqGMTQbZj5Rt7mnA==,type:str]
    identity.pub: ENC[AES256_GCM,data:JSq4N2ajh8ox/2ZHcNS0y6gE8Krfdl4Z6ZpOFwqG+qWPtW/DcYLjuIhaUUH8UzHdqbHhlFs+lnfrzKtqRGEIKDQp7iEwDASE+/PYR4tRxdVKUMSUf5e/FCNQRYYBgRf4Kbooi/x4eWn/nHU7bqvNNQTHWtPaGflEcO/YMa6IA2j63mhypY5RpiPXNEkN3v8vcUo5TMXcx2bHv4IWNNgaxcACicgaMDn7qN5AVkrAhWLbZ3plx9heAKHVlASLBzn5CfVGEFcnWQbOfuTlcQ==,iv:ifxeZI6QCIFha0eZsZnLWge2ETKtr5qr8VcTmTR9VG4=,tag:z2zF1cJBqfP5Q+c300HZrA==,type:str]
    known_hosts: ENC[AES256_GCM,data:uLVuACclIn9PK1uiolrUHPROYMfb3gD6S5ZRcQdMRT/D3isKA5Vkhuq8oGEqKC2vVslaGg+K3p9ENbAd3oRGreu02INZinnCdBquK6bXIP9pLAF6dS3n5r8aRPkqQ9Fjkbq7ATFYCgm6eifM/Tq2kqJ5QpKWhAILLhiVtRbfSbh+wNAqPrPlW3AXPiu2PM7CAyYeQDpLielGcHnWBirUEde2JEZsgL3+ijIQ,iv:FEt/iNH6DC2Blj3FVVmbrkIhdYeP/Fg7dZ7nnwarIT8=,tag:GBxM3YmFaDwEMCDz0W6y7A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1grv49vt8y6u7vse4030mgnfylx6c2jw7hlwhqs34nc9n9rpdwefqnr7vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVjhBSXl4d2FBaHladFhG
            TVNvQjhkakptekhSTmhqaUpaNmtoeWtSMW5vCjQzWmVJd2F6bjh2d09PUU5MZGVz
            ckdCWDZzelBCcTZFajU0S2tiR2JsYkUKLS0tIGF5YzZSK25YNy8vUU90K3BCTzFC
            TXFLeERkNFlOUkJFbHhESDVZWGpzVG8KLLPesBbN6rEcaTtNVdJMuX9FYWij5aCX
            NlCBiVmIxEpk+9yUeHH6jYLBhPRFTvF8KxbfN8vQKgaoQh0VVqvosg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T01:29:15Z"
    mac: ENC[AES256_GCM,data:3B2NsYWkBM1PQRHuP5cshXUWnMO/ZS6b3HlM7ILH8TQSZKkhzgf+s03sv8dvVZc+2CM0QzNyIZgwvjOQyP9PzkhLBUWNH8wHMaFP8TjtHCeQBUz+jFDdJsRZPTIg+uE9XgDq9S+dcAkQZQM3b1LPT2WGJn0vXt7zXbAHyorLuYQ=,iv:0tD/sy5+udpO7iqiqdi8BvqwtMYWAvi+skOsq/fOjp8=,tag:1pp2NE/0f6iwxE75brR7fg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
