apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jYxhpcBbX+61AmWrRVpFqazpZGXW9R707zkChzVEY0LKtm6OSuw/lJOrGRu04ymEaRQc5L3Blb6p/0GA3Sp+Dv/pyF+4XplD2WqPUCNFFdzsvapUkvlcSlJzS5tGXjaHhLOhIVHw33ZDepRP5oMoH60y6BPls7th9KwHnDItFzv34J9OtxbpZm+xkYnQqs1oAj8R1vn4idGvUM9/fDhfTYeghdxT4n6LdIIrOKBsp4zrcEHd38z3bNHnxpJBAhsi++YCMoyeWf5/DMlKKRZYt/bM4IHwW9r1safe01k16Zg63mKGObpjqH0Ksv10S2V0roW6XRaY7mZAXuYl0iOlnLjnZvNvwJON5lSHO0rQdNm/hZ819WXH0ul0lFzp+3N/,iv:Wk4S3dKfVVkReF9MlUoroCp1Mve2XYUQ3eGWEI/K+54=,tag:OPwQkZ6bCltWLL8Jd2yRQg==,type:str]
    identity.pub: ENC[AES256_GCM,data:tqAjwBRXJ7MfxCOU6mymgeobYsHZ/xJ1UF9GST+Ka+oQjCkKT01mish/fwVJWavus4pOR+06LP9k5OopNR3yc/hgt18F+PizLD43PYldDjym/5nwtf9I1qEj6CDbgY3MwS675cCbbEmlhB9S6qubx+RmNmM/y6ymgjrpTzAUm6e5HsIPOvoPIZEiYlqt5Bh38IsuT66ZwzU4x29QELF4mgrZWgSfK9wgXF97L9S8/tanqpenyHLQypORdgJXVbpILvF6rmcQ4MQn7OewBg==,iv:2vestkd5p8v3UzbRTftkT+Nqsi1ndkTFsUdgjKcczts=,tag:9a05jYi9/diS15ZnA7tUbw==,type:str]
    known_hosts: ENC[AES256_GCM,data:NPLEJkZn4RVMvaTKSQ72Zu3oD+BPBiWkyRADlvtZ4XqlHAEFwePMJOiqTuPzHUYjPqKjRiI+b6f6pK3E/9kY19fRxZQZK6qxOu5YzYqB96DJIMvFz3M2h7lnZh9rLkxfCGUSWCnmpndapWK1YxJaRdgysBRofixjr/vbjC1Wh32zHhQHhOEo/KOZtLThpp5YcaYGHo0SvSLo71e/sltpxBHHrpMp21aKC91R,iv:594wg6YD3KuVtTa6Nvd+xyb+xq9Bi7zqdK3J4zbaZ48=,tag:m0UJCQKmGLPn6ZHzEPzSDQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1grv49vt8y6u7vse4030mgnfylx6c2jw7hlwhqs34nc9n9rpdwefqnr7vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGZklQME10OCtycDdXRkla
            eHJCZG9ydGpieDRBS2c3azI3NWgwYVI2ZlRNCmQ4OFZ3MThmUVBUaWNPYitDbnZD
            YjlndU1Pa2E1dUQ2WXVZREd2bzNLNlEKLS0tIEh1QzlqNGZpOUc3TG42S01ReS9l
            d3J6Y3Jmejl5Y1ZIZXhVQ2VkK2RYOVEK7b5plqP51CwW9B7bpPdI4xUaSFNdwRQk
            l94XWonIk6x4cOB8C2gBvGjkG2Rn7nbMQuTKElF7SKzpM+Jo0o9pug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T00:26:20Z"
    mac: ENC[AES256_GCM,data:BYvdGQqsQ3iV/LgptPRjJiy4ITd/emtlO/9v4lqsT+QufP7CkKdvx0Qfr1vEu60q2wPDCn517+HaPAGrXC8zFuQfcbMO3PjIL0QacyWt+ZfkQ0IJPNhkXyDksLwINjjRNaEs/2MXUdHmovtunxBUgWGlECrxvtRVKCPPE8yCZMI=,iv:AIYY7hScwRudSDv0vB2JAExolm6GMn6nonCA9B14Rtw=,tag:WftqEtwHFAzRApUv+Hfvcg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
