apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:EPjk3LRwY6lotLVLbTgVVwUyFMjUp7j6094XrH9IQi5hkdQC3MbL2hCQkAdbIdM1dfSQPHj9efABxWEFeY/O+IXWMgjNnOm8cpbNNwtmxKleOTX8augaaQ+zRzsQjQrQxYX1fmW4rUBxpsPSKQdMfd10KW3XjmKLd8ytnP2XDzUS020EH8H9HlxCOb+Cqp7aNIP2+urV37tdb8z8ren9+4FheUNrmKm1O4X6Tf+vtM9E+KEI8TTO9SDYTms9NJPCg5eqKxkbnSuzSkOSMIcPXQtsyuFlAVPaTegc/Rodcly/Me8TF8E2Jz2WtBqmCyTobkuyQm3gYLaHx3KNyAi9i/NwFkNJTFPk8mmOGdT25gpJ6Msr+vh6uaApsRukQbw1,iv:reuTLh8NUDwconpIHhqLpN9eLpH3hkQ8rfBvd2hrwZs=,tag:hi6H0lKUxKGypRHKCiqndg==,type:str]
    identity.pub: ENC[AES256_GCM,data:sKG6IAgvvDr7opZZon35nO/Mknbum9JkDn3hsdHXdnlhewdW5cD5RoE59jjfZamo65n4czFW8FngiJaTkeJc5rOM/5i/VEDcuoTisZ35cLeODpnoTYn+ZtJYIKblepfQQw5ou8BfxkVq2qmkHZANccZm8mMog1bWZYj3S8bxfJwI4d878HTERek1effzWe9tijbASre8cp76GsTmEEhlpeLX+vczN5y/MnbUb8w3GHMOQKc1wwodjGb4GACKP1lNamEDY+ydKbA62dIWUQ==,iv:EUV87rO3+L+EpMDGuh95vDRw65b0h0Zt9AEWRHN/GKs=,tag:c1C3z/599IxVRkrXUtcJ1A==,type:str]
    known_hosts: ENC[AES256_GCM,data:/aEYSN2I8HwFym6tKTde8JJBzcHEQxpDbJPvtvl65nGj8SUT1nJXjBJzBSEiFD6OY/hoGCJWgEtIK+MooSMM1zqukKXqYnYPnmcJNblPKvJGB4vZcRkpbJ7tiivJ1ovBORpXmlP83199u0Es7aAeqlQrKZ1N/vLQ+Y0uQsdbExwbrr+TzBbhM97stRpGlYIE0/3wkb8Scw/U4ahn3of4J2B3bAXLBMscdU5L,iv:KsQgA3XkBq2Nh3/n8ef/rK2BLsaghHACGxUZyNsD9qc=,tag:XrYLJZBCa7LryIxuxO/3Bg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1grv49vt8y6u7vse4030mgnfylx6c2jw7hlwhqs34nc9n9rpdwefqnr7vjm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbldFc0xmMk5mSGpUYjRO
            N0pNSFFnQkFvU2tOMFZWeFpaY0FVRENBTkFnCkNOQ1Q3Q0hpN3A3a2czMHVQald6
            SERrSFdBS2lYODMrenc4Zjc4djU4RDAKLS0tIGtGejIxeXNYL2hURUsrd1VUVW11
            M1FMYUFpMnhFZVlRK1gvUERMTWgrdTAKzJTbf5alRzsYCgUpNWzAwPzn+Lxotf50
            EO+YVD1govzNaetv8o5fjelLv8O9KmjsziOLif6Qt1Dz1gAW0MSlEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-10T04:48:37Z"
    mac: ENC[AES256_GCM,data:hIB4cre2sbWibWYCKG7CNABYPDKXGCfVTUG+qy6m89c9xDcG1hu7JOvWaGGpixEpfUYYzVkhmBwydSrwhHXqKSNygRDCICLjJUajClDJWMuCmQj2L5TQoeMR9mRV8Qp/kkGoE70CnENYHTVVyaNMixJsFuKqoyV2EYCUBm4vAz0=,iv:dVWP4bsKzBPPlWd9mmbemAtZ9s1ziQvP12TEbxRhsoQ=,tag:ROjijGkJ7Coyu3fcRp+0bQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
